from __future__ import annotations

from pathlib import Path
from typing import Any

SURFACE_STRENGTH_MODEL_REF = "docs/SURFACE_STRENGTH_MODEL.md"


def _surface(
    *,
    name: str,
    surface_ref: str,
    schema_ref: str,
    primary_question: str,
    derivation_rule: str,
    input_posture: str,
    owner_truth_inputs: list[str],
    authority_ceiling: str,
    consumer_risk: str,
    live_state_capable: bool,
) -> dict[str, Any]:
    return {
        "name": name,
        "surface_ref": surface_ref,
        "schema_ref": schema_ref,
        "primary_question": primary_question,
        "derivation_rule": derivation_rule,
        "input_posture": input_posture,
        "owner_truth_inputs": owner_truth_inputs,
        "authority_ceiling": authority_ceiling,
        "consumer_risk": consumer_risk,
        "live_state_capable": live_state_capable,
    }


SURFACE_SPECS = [
    _surface(
        name="core_skill_application_summary",
        surface_ref="generated/core_skill_application_summary.min.json",
        schema_ref="schemas/core-skill-application-summary.schema.json",
        primary_question="Which project-core kernel skills are actually finishing and how often, without inferring usage from general receipt volume?",
        derivation_rule="aggregate core_skill_application_receipt payloads by kernel_id and skill_name",
        input_posture="receipt_backed_live",
        owner_truth_inputs=["aoa-skills owner-local receipts"],
        authority_ceiling="Weaker than owner-local skill execution records and any reviewed owner closeout.",
        consumer_risk="medium",
        live_state_capable=True,
    ),
    _surface(
        name="object_summary",
        surface_ref="generated/object_summary.min.json",
        schema_ref="schemas/object-summary.schema.json",
        primary_question="How often and how broadly is each source object showing up in the current receipt feed?",
        derivation_rule="group receipts by object_ref and keep counts, latest timestamps, and bounded posture flags",
        input_posture="receipt_backed_live",
        owner_truth_inputs=["owner-local receipts across the active registry"],
        authority_ceiling="Weaker than the owner repos named in object_ref and weaker than any linked evidence surface.",
        consumer_risk="low",
        live_state_capable=True,
    ),
    _surface(
        name="candidate_lineage_summary",
        surface_ref="generated/candidate_lineage_summary.min.json",
        schema_ref="schemas/candidate_lineage_summary.schema.json",
        primary_question="How far are reviewed growth-refinery candidates actually moving without turning stats into routing or proof authority?",
        derivation_rule="aggregate reviewed-only candidate_lineage_entries carried on harvest_packet_receipt payloads into stage, owner-target, posture, misroute, supersession, and time-to-stage summaries",
        input_posture="receipt_backed_live",
        owner_truth_inputs=["aoa-skills reviewed harvest receipts"],
        authority_ceiling="Weaker than reviewed owner-local lineage records and any owner landing surface.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="owner_landing_summary",
        surface_ref="generated/owner_landing_summary.min.json",
        schema_ref="schemas/owner-landing-summary.schema.json",
        primary_question="Which reviewed candidates have landed in owner-local status surfaces and how far has that landing stabilized without turning stats into owner truth?",
        derivation_rule="aggregate reviewed_owner_landing_receipt payloads together with seed_owner_landing_trace_receipt payloads into owner-repo, posture, outcome, and time-to-outcome summaries",
        input_posture="receipt_backed_live",
        owner_truth_inputs=["aoa-skills reviewed owner landing receipts", "Dionysus seed owner landing traces"],
        authority_ceiling="Weaker than owner-local status surfaces, reviewed landing bundles, and owner repository decisions.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="supersession_drop_summary",
        surface_ref="generated/supersession_drop_summary.min.json",
        schema_ref="schemas/supersession-drop-summary.schema.json",
        primary_question="What pruning, replacement, merge, and reanchor signals are explicit across reviewed growth-refinery receipts without inventing reasons or ranking authority?",
        derivation_rule="aggregate reviewed candidate-lineage entries, reviewed_owner_landing_receipt payloads, and seed_owner_landing_trace_receipt payloads into explicit turnover summaries",
        input_posture="receipt_backed_live",
        owner_truth_inputs=["aoa-skills reviewed harvest receipts", "aoa-skills reviewed owner landing receipts", "Dionysus seed owner landing traces"],
        authority_ceiling="Weaker than reviewed turnover records and any owner-local acceptance or rejection rationale.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="repeated_window_summary",
        surface_ref="generated/repeated_window_summary.min.json",
        schema_ref="schemas/repeated-window-summary.schema.json",
        primary_question="What changed across bounded date windows without turning the result into one global score?",
        derivation_rule="group receipts by observed_at date and keep counts plus bounded window signals",
        input_posture="receipt_backed_live",
        owner_truth_inputs=["owner-local receipts across the active registry"],
        authority_ceiling="Weaker than the underlying receipt feed and any owner-local chronology or closeout record.",
        consumer_risk="medium",
        live_state_capable=True,
    ),
    _surface(
        name="route_progression_summary",
        surface_ref="generated/route_progression_summary.min.json",
        schema_ref="schemas/route-progression-summary.schema.json",
        primary_question="What bounded multi-axis movement is visible on each named route?",
        derivation_rule="aggregate progression_delta_receipt payloads by route_ref and sum axis deltas",
        input_posture="receipt_backed_live",
        owner_truth_inputs=["owner-local progression receipts"],
        authority_ceiling="Weaker than owner-local route records, playbooks, and progression decisions.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="fork_calibration_summary",
        surface_ref="generated/fork_calibration_summary.min.json",
        schema_ref="schemas/fork-calibration-summary.schema.json",
        primary_question="How are route forks actually being chosen and how often do they carry realized outcome refs?",
        derivation_rule="aggregate decision_fork_receipt payloads by route_ref and chosen_branch",
        input_posture="receipt_backed_live",
        owner_truth_inputs=["aoa-skills decision fork receipts"],
        authority_ceiling="Weaker than owner-local route selection and any reviewed followthrough outcome.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="session_growth_branch_summary",
        surface_ref="generated/session_growth_branch_summary.min.json",
        schema_ref="schemas/session-growth-branch-summary.schema.json",
        primary_question="What reviewed next-kernel branches are being recommended after closeout without turning stats into route authority?",
        derivation_rule="aggregate reviewed followthrough hints carried on decision_fork_receipt payloads into next-skill, owner-target, posture, defer, and reason-code counts",
        input_posture="receipt_backed_live",
        owner_truth_inputs=["aoa-skills reviewed decision fork receipts"],
        authority_ceiling="Weaker than any owner-local route fork, playbook, or approval surface.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="automation_pipeline_summary",
        surface_ref="generated/automation_pipeline_summary.min.json",
        schema_ref="schemas/automation-pipeline-summary.schema.json",
        primary_question="How close is a named automation pipeline to seed-ready bounded use?",
        derivation_rule="aggregate automation_candidate_receipt payloads by pipeline_ref and readiness flags",
        input_posture="receipt_backed_live",
        owner_truth_inputs=["aoa-skills automation candidate receipts"],
        authority_ceiling="Weaker than owner-local approval, playbook, and runtime rollout surfaces.",
        consumer_risk="medium",
        live_state_capable=True,
    ),
    _surface(
        name="automation_followthrough_summary",
        surface_ref="generated/automation_followthrough_summary.min.json",
        schema_ref="schemas/automation-followthrough-summary.schema.json",
        primary_question="How far are reviewed automation candidates moving through bounded follow-through without implying scheduler authority?",
        derivation_rule="aggregate automation_candidate_receipt payloads into seed-ready, defer, checkpoint, playbook-seed, real-run-review, and blocker counts",
        input_posture="receipt_backed_live",
        owner_truth_inputs=["aoa-skills automation candidate receipts"],
        authority_ceiling="Weaker than owner-local automation approval, runtime execution, and reviewed followthrough surfaces.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="codex_plane_deployment_summary",
        surface_ref="generated/codex_plane_deployment_summary.min.json",
        schema_ref="schemas/codex-plane-deployment-summary.schema.json",
        primary_question="What is the current derived deployment continuity posture for the shared-root Codex plane without letting stats overrule live trust evidence?",
        derivation_rule="derive one bounded deployment summary from the 8Dionysus trust-state and rollout receipt examples plus the aoa-sdk deploy-status example",
        input_posture="checked_in_owner_history",
        owner_truth_inputs=["8Dionysus checked-in trust-state surfaces", "aoa-sdk deploy-status example"],
        authority_ceiling="Weaker than 8Dionysus rollout history, trust-state receipts, and aoa-sdk deployment status.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="codex_rollout_operations_summary",
        surface_ref="generated/codex_rollout_operations_summary.min.json",
        schema_ref="schemas/codex-rollout-operations-summary.schema.json",
        primary_question="What checked-in trusted rollout campaign posture is currently visible for the shared-root Codex plane without turning stats into rollout authority?",
        derivation_rule="derive bounded rollout state counts and latest campaign posture from 8Dionysus checked-in generated/codex/rollout source surfaces",
        input_posture="checked_in_owner_history",
        owner_truth_inputs=["8Dionysus generated/codex/rollout history"],
        authority_ceiling="Weaker than source-owned rollout history and rollback windows.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="codex_rollout_drift_summary",
        surface_ref="generated/codex_rollout_drift_summary.min.json",
        schema_ref="schemas/codex-rollout-drift-summary.schema.json",
        primary_question="What is the current bounded drift and rollback posture of the latest trusted Codex rollout campaign without replacing source-owned campaign history?",
        derivation_rule="derive the latest drift window, drift state, repair attempt posture, and rollback requirement from 8Dionysus checked-in rollout history and rollback windows",
        input_posture="checked_in_owner_history",
        owner_truth_inputs=["8Dionysus generated/codex/rollout history", "8Dionysus rollback windows"],
        authority_ceiling="Weaker than source-owned drift reviews, rollback windows, and campaign history.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="rollout_campaign_summary",
        surface_ref="generated/rollout_campaign_summary.min.json",
        schema_ref="schemas/rollout-campaign-summary.schema.json",
        primary_question="What is the current bounded campaign cadence posture for the shared-root Codex plane without turning stats into cadence authority?",
        derivation_rule="derive one current campaign-cadence summary from 8Dionysus source-owned rollout campaign, drift-review, and rollback-followthrough window examples",
        input_posture="checked_in_owner_history",
        owner_truth_inputs=["8Dionysus rollout campaign window examples"],
        authority_ceiling="Weaker than source-owned campaign cadence and review decisions.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="drift_review_summary",
        surface_ref="generated/drift_review_summary.min.json",
        schema_ref="schemas/drift-review-summary.schema.json",
        primary_question="What named drift signals and explicit review decisions are currently visible in the source-owned cadence windows without replacing rollout or campaign truth?",
        derivation_rule="derive one bounded drift-review summary from the current 8Dionysus cadence windows and keep rollback readiness descriptive only",
        input_posture="checked_in_owner_history",
        owner_truth_inputs=["8Dionysus drift review windows"],
        authority_ceiling="Weaker than source-owned drift reviews, campaign windows, and rollback decisions.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="continuity_window_summary",
        surface_ref="generated/continuity_window_summary.min.json",
        schema_ref="schemas/continuity-window-summary.schema.json",
        primary_question="What is the current bounded self-agency continuity posture without turning stats into continuity truth or self-agency proof?",
        derivation_rule="derive one bounded continuity snapshot from the aoa-agents continuity window example, the sovereign continuity playbook, the memo-side provenance thread example, and the landed continuity eval anchors",
        input_posture="reviewed_example_chain",
        owner_truth_inputs=["aoa-agents continuity examples", "aoa-playbooks continuity playbook", "aoa-memo provenance thread example", "aoa-evals eval anchors"],
        authority_ceiling="Weaker than continuity anchor artifacts, memo provenance threads, and bounded eval proof.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="component_refresh_summary",
        surface_ref="generated/component_refresh_summary.min.json",
        schema_ref="schemas/component-refresh-summary.schema.json",
        primary_question="What is the current bounded component refresh posture across named owner repos without letting stats become refresh truth or maintenance authority?",
        derivation_rule="derive one bounded component refresh snapshot from reviewed aoa-sdk drift hints and reviewed followthrough decisions while keeping owner validation stronger",
        input_posture="reviewed_example_chain",
        owner_truth_inputs=["aoa-sdk reviewed drift hints", "reviewed followthrough decisions"],
        authority_ceiling="Weaker than owner repo refresh law, owner validation, and real regeneration evidence.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="titan_incarnation_summary",
        surface_ref="generated/titan_incarnation_summary.min.json",
        schema_ref="schemas/titan_incarnation_summary.schema.json",
        primary_question="What bounded Titan incarnation seed posture is visible without making stats the owner of Titan identity or gates?",
        derivation_rule="derive fixed seed counts from the landed Titan XV owner surfaces and keep source receipt refs explicit",
        input_posture="reviewed_example_chain",
        owner_truth_inputs=[
            "Dionysus fifteenth wave manifest",
            "aoa-agents Titan incarnation identity surface",
            "aoa-sdk Titan incarnation spine defaults",
        ],
        authority_ceiling="Weaker than Dionysus seed lineage, aoa-agents role identity, aoa-sdk runtime helpers, and owner review evidence.",
        consumer_risk="high",
        live_state_capable=False,
    ),
    _surface(
        name="titan_summon_summary",
        surface_ref="generated/titan_summon_summary.min.json",
        schema_ref="schemas/titan_summon_summary.schema.json",
        primary_question="What seed-level Titan summon/report/finding/memory-candidate pressure is visible without making stats the owner of swarm ledger truth?",
        derivation_rule="publish the Sixteenth Wave seed summary until owner-local Titan swarm ledgers and closeout receipts provide a live feed",
        input_posture="seed_static_summary",
        owner_truth_inputs=[
            "Dionysus sixteenth wave manifest",
            "aoa-sdk Titan swarm ledger helper",
            "Titan closeout audit receipts",
        ],
        authority_ceiling="Weaker than Titan swarm ledgers, closeout audits, owner-local reports, and bounded eval verdicts.",
        consumer_risk="high",
        live_state_capable=False,
    ),
    _surface(
        name="runtime_closeout_summary",
        surface_ref="generated/runtime_closeout_summary.min.json",
        schema_ref="schemas/runtime-closeout-summary.schema.json",
        primary_question="What is the current bounded runtime closeout posture across program waves and how did reviewed handoff land?",
        derivation_rule="aggregate runtime_wave_closeout_receipt payloads by program_id and wave_id and keep the latest gate plus handoff posture",
        input_posture="receipt_backed_live",
        owner_truth_inputs=["abyss-stack runtime closeout receipts"],
        authority_ceiling="Weaker than owner-local runtime closeout records, gates, and handoff evidence.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="stress_recovery_window_summary",
        surface_ref="generated/stress_recovery_window_summary.min.json",
        schema_ref="schemas/stress-recovery-window-summary.schema.json",
        primary_question="What does the current repeated-window stress recovery proof family say without inventing a new canonical event kind or outranking owner evidence?",
        derivation_rule="resolve aoa-stress-recovery-window eval_result_receipt report_ref paths through aoa-evals and derive one bounded summary plus suppression posture",
        input_posture="receipt_backed_with_external_reports",
        owner_truth_inputs=["aoa-evals eval result receipts", "aoa-evals stress recovery reports"],
        authority_ceiling="Weaker than owner-local stressor receipts, bounded eval reports, and route-owner recovery guidance.",
        consumer_risk="high",
        live_state_capable=True,
    ),
    _surface(
        name="source_coverage_summary",
        surface_ref="generated/source_coverage_summary.min.json",
        schema_ref="schemas/source-coverage-summary.schema.json",
        primary_question="Which owner repos and receipt families are actually entering the active stats feed, and where is the stats layer still blind?",
        derivation_rule="aggregate active receipts by object_ref.repo and event_kind, then compare observed owners against the configured live source registry when present",
        input_posture="registry_backed_coverage_audit",
        owner_truth_inputs=["config/live_receipt_sources.json", "owner-local receipts across the active registry"],
        authority_ceiling="Weaker than the owner-local receipt logs and weaker than the live source registry it audits.",
        consumer_risk="medium",
        live_state_capable=True,
    ),
    _surface(
        name="surface_detection_summary",
        surface_ref="generated/surface_detection_summary.min.json",
        schema_ref="schemas/surface-detection-summary.schema.json",
        primary_question="What second-wave surface-detection signals are accumulating without turning stats into routing authority?",
        derivation_rule="aggregate advisory surface_detection_context payloads on finish-stage core_skill_application_receipt envelopes by observed date",
        input_posture="receipt_backed_live",
        owner_truth_inputs=["aoa-skills core skill application receipts"],
        authority_ceiling="Weaker than owner-local route decisions and weaker than aoa-sdk or aoa-routing dispatch surfaces.",
        consumer_risk="high",
        live_state_capable=True,
    ),
]

DEFERRED_CONTRACT_SURFACES = [
    {
        "name": "antifragility_vector",
        "status": "contract_only",
        "contract_ref": "docs/ANTIFRAGILITY_VECTOR.md",
        "schema_ref": "schemas/antifragility_vector_v1.json",
        "activation_condition": "Activate only after one owner-linked repeated-window receipt family and bounded eval chain exist for the same stressor family.",
        "authority_ceiling": "Even after activation this surface stays weaker than owner-local stressor receipts and bounded eval reports.",
    }
]


def build_summary_surface_catalog(
    source: dict[str, Any], *, available_output_names: set[str] | None = None
) -> dict[str, Any]:
    surfaces = SURFACE_SPECS
    if available_output_names is not None:
        surfaces = [
            surface
            for surface in SURFACE_SPECS
            if Path(surface["surface_ref"]).name in available_output_names
        ]
    return {
        "schema_version": "aoa_stats_summary_surface_catalog_v2",
        "schema_ref": "schemas/summary-surface-catalog.schema.json",
        "owner_repo": "aoa-stats",
        "surface_kind": "runtime_surface",
        "authority_ref": "docs/ARCHITECTURE.md",
        "surface_strength_model_ref": SURFACE_STRENGTH_MODEL_REF,
        "generated_from": source,
        "validation_refs": [
            "scripts/build_views.py",
            "scripts/validate_repo.py",
            "tests/test_summary_surface_catalog.py",
        ],
        "deferred_contract_surfaces": DEFERRED_CONTRACT_SURFACES,
        "surfaces": surfaces,
    }
